### ISSUE TITLE
When sending transaction: ERROR Failed to get random outputs

### ISSUE THREAD

**Issue by CoinLogik** [valiant1x/intensecoin#26]
- RPC JSON call sent to `walletd`: 
```
{
    "method": "sendTransaction",
    "jsonrpc": "2.0",
    "id": "test",
    "params": {
        "transfers": [{
            "amount": 35366991023900,
            "address": "iz51...."
        }, {
            "amount": 2257467570300,
            "address": "iz52..."
        }, {
            "amount": 23263953575900,
            "address": "iz53..."
        }],
        "fee": 100000,
        "anonymity": 3,
        "unlock_time": 0
    }
}
```

walletd logs:
```
ERROR   Failed to get random outputs: NodeErrorCategory:5, Internal node error
WARNING Error while sending transaction: Internal node error
```

and returns JSON response:

```{"code":-32000,"data":{"application_code":5},"message":"Internal node error"}```

What's the cause? Are amounts too big? I'm on a test net, so the wallets are fat.

**Comment by valiant1x** [comment]
Reduce the level of anonymity and/or reduce precision. Although your wallets are phat, the outputs in your wallet are still not massive in size, and due to the lack of transactions on the testnet it's harder to mix other transactions in. Mixins also become more difficult as you use micro amounts of coins (eg. 23263953575900 is 232639.53575900, smallest unit = 0.000009) - every single non-zero decimal place is split up into its own group of outputs.

**Comment by CoinLogik** [comment]
Interesting.... so should I use anonymity of 0 in testnet but 4 in real net? Would it help if I rounded payments down? e.g. instead of sending 232639.53575900, send 232639.53500000?

**Comment by valiant1x** [comment]
You can experiment with using as many mixins as is permissible but given the complete absence of txns on testnet you will likely need to use 0. Rounding payments down - yes, that is what I meant by reducing precision
