### ISSUE TITLE
Orphaned block in pools

### ISSUE THREAD

**Issue by KhmerRun** [valiant1x/intensecoin#40]
Hello,

I tried to understand the orphaned block by searching some topics in Google already. If you think it is not worth to answer, issue can be closed.

I have a small personal pool which just recently found a block and it stated that the block is orphaned. Will reward still come to us or to other pool? I checked the balance of pool wallet and saw reward given with X amount of ITNS but wallet of the pool didn't spread to miners for the reason of orphaned.

Regards,

**Comment by KhmerRun** [comment]
For your information, after update the source from github. I got two orphaned blocks in a row.

**Comment by valiant1x** [comment]
If you updated the core daemon/wallet code without updating your pool, it will not work. The rebase is not compatible with pre-rebase pools. Your issue of displayed orphans (not real orphans) is due to pre-rebase pool software adding `+1` to `getblockheaderbyheight` and `getblockheight` RPCs. In any case, your best option is switching to [Venthos ITNS nodejs-pool repo](https://github.com/Venthos/nodejs-pool), which is designed and maintained for the rebase.
