### ISSUE TITLE
Daemon does not want to accept any more blocks at height 166599

### ISSUE THREAD

**Issue by minerrocks** [valiant1x/intensecoin#67]
Daemon does not want to accept any more blocks at height 166599

https://github.com/valiant1x/intensecoin/blob/e60b3da93e809446f545ace4ed0b112c8a214190/src/cryptonote_core/cryptonote_core.cpp#L1049

`2018-04-19 21:33:58.639 [RPC0] ERROR cn src/cryptonote_core/cryptonote_core.cpp:1049 mined block failed verification`

**Comment by valiant1x** [comment]
The daemon exploded at block 167000. It seems there is special logic every 1000 blocks to prepare some sections of the database. When it tried to prepare the previous batch of 1000 blocks at 167k, somehow it absorbed the v3 fork. It seems to have placed any databases that were active at that time into an unrecoverable and corrupt state, leaving them in an odd v4-v3 fork hybrid state. Popping the blocks does not work as the number of already generated coins became based on the old v3 chain, and therefore the v4 chain is unable to make new coins because the block rewards don't match up.

I believe this was due to the absence of checkpoints at 166134 or later. In the absence of definitive checkpoints, despite the software being instructed to fork v4 at block 166134, it took the liberty of reverting to v3 at 167k. I have updated the checkpoint file and corresponding hash in the code. 

To resolve: You will need to `git pull` the latest commit (5688302) and rebuild. That should resolve issues with forking again at 167k.

For now, your blockchain is corrupt. I'm not sure if the database will autocorrect when the network reaches 167k again, but if you want to use the daemon between now and then, you will also need to completely wipe your database and either re-sync from scratch or sync the [bootstrap/snapshot file](https://github.com/valiant1x/intensecoin/releases/tag/v1.45-snap).

**Comment by BKdilse** [comment]
Just saw this today too.

After compiling new daemon, do I have to remove the blockchain, or only remove it if it does not progress further?

**Comment by mtl1979** [comment]
If it does stop syncing, just run:

`intense-blockchain-import --pop-blocks <n> --drop-hard-fork`

On first attempt, `<n>` should be last three numbers of current local block height

Then re-run `intensecoind` with same parameters as last time. If it gets stuck more than once, you can use smaller `<n>` to revert to previous block height that you did rewind from (usually 166600, 166850, ...).

**Comment by minerrocks** [comment]
The issue is resolved as network goes further, it was not about syncing, but about daemon refuse mined blocks
