### ISSUE TITLE
Wallet sync

### ISSUE THREAD

**Issue by Beanong** [valiant1x/intensecoin#78]
Is it normal the very slow sync process is normal after the hard fork? My wallet sync node would never catch up with top node: ( im using the latest cli wallet fyi

**Comment by valiant1x** [comment]
It's moving slower because there are still many v3 nodes on the network that need to update their software. It should speed up as we get more v4 consensus. 

Also consider that sync until the v4 hardfork will be noticeably faster than future blocks until we update the checkpoints again. Checkpoints were updated at block 166500 or so.
